name: Compose
password:
  value:
    length:
      min: 6
  reset:
    flow:
      request:
        url: https://app.compose.io/password_resets/new
        form:
          email:
            input: required
      response:
        email:
          sender: support@compose.io
          body: [url]
        expire: 15m
      change:
        form:
          newpassword:
            characters: masked
          repeat:
            newpassword:
              input: required
              characters: masked
      submit:
        sessions:
          own: unchanged
        expire: unchanged
  change:
    url: https://app.compose.io/account#user_current_password
    form:
      oldpassword:
        input: required
        characters: masked
      newpassword:
        characters: masked
      repeat:
        newpassword:
          input: required
          characters: masked
registration:
  url: https://compose.com/signup
  form:
    fullname:
      input: required
    email:
      input: required
    password:
      input: required
      characters: masked
    repeat:
      email:
        input: none
      password:
        input: none
login:
  url: https://app.compose.io/session/new
  form:
    email:
      input: required
    password:
      characters: masked
reviewed:
  date: 2017-02-21T06:20:36.743Z
