name: Compose
password:
  value:
    length:
      min: 8
      max: 999
  reset:
    url: https://app.compose.io/users/password/new
    flow:
      request:
        form:
          account:
            accepts: email
      response:
        email:
          sender: support@compose.io
          body: url
      submit:
        sessions:
          own: unchanged # assumed based on previous "token.login: no"
  change:
    url: https://app.compose.io/account
    # reauth value was "maybe" (???), review pending - see issue #170
registration:
  url: https://app.compose.io/signup/svelte
login:
  url: https://app.compose.io/
reviewed:
  date: 2015-06-20T19:29:04.756Z
